apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shop
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/shop
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra