apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qvcoaching
  annotations:
    cert-manager.io/issuer: qvcoaching
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: external
  rules:
    - host: qvcoaching.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qvcoaching
                port:
                  number: 3000
  tls:
   - hosts:
       - qvcoaching.fr
     secretName: tls-qvcoaching
