apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qvcoaching
resources:
  - service.yaml
  - namespace.yaml
  - deploy.yaml
  - external-secret.yml
  - issuer.yml
  - listenerset.yaml
  - httproute.yaml
