apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prestashop
  annotations:
    cert-manager.io/cluster-issuer: bealvio
    external-dns.alpha.kubernetes.io/target: bealv.io
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: external
  rules:
    - host: shop.bealv.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prestashop
                port:
                  number: 80
  tls:
   - hosts:
       - shop.bealv.io
     secretName: tls-shop
