apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop
resources:
  - deploy.yml
  - service.yml
  - namespace.yml
  - external-secret.yml
  - statefulset-mariadb.yml
  - httproute.yaml
