apiVersion: v1
kind: Service
metadata:
  name: prestashop
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: prestashop
    role: web
---
apiVersion: v1
kind: Service
metadata:
  name: prestashop-mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mariadb
  selector:
    app: mariadb
    part-of: prestashop